database:
 host: "127.0.0.1"
 port: 5432
 user: "username"
 password: "password"
 dbname: "dbname"

app:
 app_id: "cli_1234567"
 app_secret: "app_secret"

server:
 host: "127.0.0.1"
 port: "8888"

publicUrl:
 callbackUrl: "http://127.0.0.1:8888/callback"
 loginUrl: "http://127.0.0.1:8888/login"
 # 飞书认证后跳转到callback后再跳转的目的页面
 frontentUrl: "http://127.0.0.1:8888/home"


